[LINKEDIN_CONFIGURATION]
API_KEY = "xxxxxxxxxxxxxxxx";
API_SECRET = "xxxxxxxxxxxxx";
REDIRECT_URI = "http://localhost/linkedin/index.php";
SESSION_NAME = "linkedin";
LINKEDIN_BASE_URL = "LinkedIn"
OAUTH_URL = "https://www.linkedin.com/uas/oauth2/authorization?"
ACCESS_TOKEN_URL = "https://www.linkedin.com/uas/oauth2/accessToken?"
RESPONSE_TYPE = "code";
SCOPE ="r_basicprofile r_emailaddress r_network";
AUTH_CODE = "authorization_code";
CACHE_FILE_EXPIRY_SECS = 300;
