[LINKEDIN_CONFIGURATION]
API_KEY = "gTt6dVtwCia-vLpjXjzxDP4TK6WS8g9bEidCDhaP76kpJ_wHOPbTsgONNkgElLCW";
API_SECRET = "9tizhz4xUG2w-XBHskRszNv0aiYWioRLzTlz6IcBxN19iVKb8iMEz2bIuAmEjABg";
REDIRECT_URI = "http://localhost/linkedin/index.php";
SESSION_NAME = "linkedin";
LINKEDIN_BASE_URL = "LinkedIn"
OAUTH_URL = "https://www.linkedin.com/uas/oauth2/authorization?"
ACCESS_TOKEN_URL = "https://www.linkedin.com/uas/oauth2/accessToken?"
RESPONSE_TYPE = "code";
SCOPE ="r_basicprofile r_emailaddress r_network";
AUTH_CODE = "authorization_code";
CACHE_FILE_EXPIRY_SECS = 1800;